/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stois.AdminPart.Diagnosis;

import Controller.DiagnosisJpaController;
import Controller.exceptions.NonexistentEntityException;
import entity.Diagnosis;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;

/**
 *
 * @author Lukas
 */
public class DeleteDiagnosisGUI extends javax.swing.JFrame {

    /**
     * Creates new form ToolGUI
     */
    
    private static EntityManagerFactory emf = null;
    private static List <Diagnosis> diagEntities = null;
    Integer index = null;
    
    public DeleteDiagnosisGUI(EntityManagerFactory emf) {
        initComponents();
        this.emf = emf;
        setDefaultCloseOperation(DeleteDiagnosisGUI.DISPOSE_ON_CLOSE);
        updateList();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JtextCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JButtDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtFind = new javax.swing.JButton();
        jButtInDatabase = new javax.swing.JButton();
        list1 = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jButtonCanceled = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonAddBAck = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDiagNote = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Delete diagnosis");

        JtextCode.setText("Diagnosis code");

        jLabel2.setText("Diganosis code:");

        JButtDelete.setText("Delete");
        JButtDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtDeleteMouseClicked(evt);
            }
        });

        jLabel4.setText("FIND");

        jButtFind.setText("Find");
        jButtFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtFindMouseClicked(evt);
            }
        });

        jButtInDatabase.setText("In database");
        jButtInDatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtInDatabaseMouseClicked(evt);
            }
        });

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });

        jLabel3.setText("Diagnosis code:");

        jButtonCanceled.setText("Canceled");
        jButtonCanceled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCanceledMouseClicked(evt);
            }
        });

        jLabel5.setText("Status");

        jButtonAddBAck.setText("ADD");
        jButtonAddBAck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddBAckMouseClicked(evt);
            }
        });

        jTextDiagNote.setColumns(20);
        jTextDiagNote.setRows(5);
        jScrollPane1.setViewportView(jTextDiagNote);

        jLabel6.setText("Diagnosis note:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtInDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(93, 93, 93))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(JtextCode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jButtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(59, 59, 59))
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(83, 83, 83)))))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAddBAck, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButtonCanceled, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(5, 5, 5)
                                .addComponent(JtextCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jButtFind)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddBAck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtInDatabase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCanceled))
                    .addComponent(jScrollPane1))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtDeleteMouseClicked
        // TODO add your handling code here:
     
        DiagnosisJpaController djc = new DiagnosisJpaController(emf);
        
        diagEntities.stream().forEach((currDiag) -> {
            if(currDiag.toString().equals(list1.getSelectedItem().toString())){
                currDiag.setCanceled(true);
                System.out.println("Canceled");
                System.out.println(currDiag.toString());
                System.out.println(currDiag.getCanceled());
                try {
                    djc.edit(currDiag);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(DeleteDiagnosisGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(DeleteDiagnosisGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        
        updateList();
        
        // vymazani natvrdo
        /*
        try {
            tjc.destroy(selectedNum);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(DeleteToolGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalOrphanException ex) {
            Logger.getLogger(DeleteToolGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        
        // ale ja budu jen cancelovat, tudiz nastavovat paramter canceled na true
        
        
        
        
        
        
    }//GEN-LAST:event_JButtDeleteMouseClicked

    private void updateList(){
    
        list1.removeAll();
        
        // tool controler
        DiagnosisJpaController djc = new DiagnosisJpaController(emf);
        
        //nalezeni si id podle kodu
        diagEntities = djc.findDiagnosisEntities();      
        
        diagEntities.stream().forEach((currDiag) -> {
            if(currDiag.getCanceled()==false){
            System.out.println(currDiag.toString());
            list1.add(currDiag.toString());          
            }
        }); 
        
    }
    
    
    private void jButtFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtFindMouseClicked
        // TODO add your handling code here:
       
        //ToolsJpaController tjc = new ToolsJpaController(emf);
        list1.removeAll();     
        // jmeno hledaneho obejktu
        
        String foundCode;
        foundCode = JtextCode.getText();

        diagEntities.stream().forEach((currDiag) -> {
            if(currDiag.getDiagnosecode().equals(foundCode)){
                list1.add(currDiag.toString());
            }
        });
        
    }//GEN-LAST:event_jButtFindMouseClicked

    private void jButtInDatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtInDatabaseMouseClicked
        // TODO add your handling code here:
       
        list1.removeAll();
       
        diagEntities.stream().forEach((currDiag) -> {
            if(currDiag.getCanceled()==false){
            System.out.println(currDiag.toString());    
            list1.add(currDiag.toString());
            }
        }); 
        
        
        
    }//GEN-LAST:event_jButtInDatabaseMouseClicked

    private void jButtonCanceledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCanceledMouseClicked
        // TODO add your handling code here:
        
        list1.removeAll();
        /*
        // tool controler
        ToolsJpaController tjc = new ToolsJpaController(emf);
        
        toolsEntities = tjc.findToolsEntities();
        */        
        diagEntities.stream().forEach((currDiag) -> {
            if(currDiag.getCanceled()==true){
            System.out.println(currDiag.toString());    
            list1.add(currDiag.toString());
            }
        });
        
        
        
    }//GEN-LAST:event_jButtonCanceledMouseClicked

    private void jButtonAddBAckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBAckMouseClicked
        // TODO add your handling code here:
        
        DiagnosisJpaController djc = new DiagnosisJpaController(emf);
        
        diagEntities.stream().forEach((currDiag) -> {
            if(currDiag.toString().equals(list1.getSelectedItem().toString())){
                currDiag.setCanceled(false);
                System.out.println("Back in database");
                System.out.println(currDiag.getCanceled());
                try {
                    djc.edit(currDiag);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(DeleteDiagnosisGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(DeleteDiagnosisGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        updateList();
        
    }//GEN-LAST:event_jButtonAddBAckMouseClicked

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        // TODO add your handling code here:
        Integer clicked = list1.getSelectedIndex();
        
        /*
        diagEntities.stream().forEach((currDiag) -> {
            if(currDiag.toString().equals(clicked)){
            System.out.println(currDiag.toString()); 
            index = currDiag.getDiagnoseid();
            //list1.add(currDiag.toString());
            }
        });
        */
        //System.out.println(index);
        jTextDiagNote.setText(diagEntities.get(clicked).getDiagnosenote());
        
    }//GEN-LAST:event_list1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDiagnosisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDiagnosisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDiagnosisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDiagnosisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteToolGUI(emf).setVisible(true);
            }
        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteToolGUI(emf).setVisible(true);
            }
        });
        */
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtDelete;
    private javax.swing.JTextField JtextCode;
    private javax.swing.JButton jButtFind;
    private javax.swing.JButton jButtInDatabase;
    private javax.swing.JButton jButtonAddBAck;
    private javax.swing.JButton jButtonCanceled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextDiagNote;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
