/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stois.AdminPart.Material;


import Controller.MaterialsJpaController;
import Controller.ToolsJpaController;
import Controller.exceptions.IllegalOrphanException;
import Controller.exceptions.NonexistentEntityException;
import entity.Materials;
import entity.Tools;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Lukas
 */
public class DeleteMaterialGUI extends javax.swing.JFrame {

    /**
     * Creates new form ToolGUI
     */
    
    private static EntityManagerFactory emf = null;
    private static List <Materials> materialsEntities = null;
    
    public DeleteMaterialGUI(EntityManagerFactory emf) {
        initComponents();
        this.emf = emf;
        setDefaultCloseOperation(DeleteMaterialGUI.DISPOSE_ON_CLOSE);
        updateList();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JtextName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JButtDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtFind = new javax.swing.JButton();
        jButtInDatabase = new javax.swing.JButton();
        list1 = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jButtonCanceled = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonAddBAck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Delete material");

        JtextName.setText("Material name");

        jLabel2.setText("Material name");

        JButtDelete.setText("Delete");
        JButtDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtDeleteMouseClicked(evt);
            }
        });

        jLabel4.setText("FIND");

        jButtFind.setText("Find");
        jButtFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtFindMouseClicked(evt);
            }
        });

        jButtInDatabase.setText("In database");
        jButtInDatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtInDatabaseMouseClicked(evt);
            }
        });

        jLabel3.setText("Material name");

        jButtonCanceled.setText("Canceled");
        jButtonCanceled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCanceledMouseClicked(evt);
            }
        });

        jLabel5.setText("Status");

        jButtonAddBAck.setText("ADD");
        jButtonAddBAck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddBAckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(93, 93, 93)))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(JtextName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(67, 67, 67))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(86, 86, 86))
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonAddBAck, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JButtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtInDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCanceled, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(JtextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButtFind)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddBAck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtInDatabase)
                    .addComponent(jButtonCanceled))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtDeleteMouseClicked
        // TODO add your handling code here:
     
        MaterialsJpaController mjc = new MaterialsJpaController(emf);
        
        materialsEntities.stream().forEach((currMat) -> {
            if(currMat.toString().equals(list1.getSelectedItem().toString())){
                currMat.setCanceled(true);
                System.out.println("Canceled");
                System.out.println(currMat.toString());
                System.out.println(currMat.getCanceled());
                try {
                    mjc.edit(currMat);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(DeleteMaterialGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(DeleteMaterialGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        
        updateList();
                         
        
    }//GEN-LAST:event_JButtDeleteMouseClicked

    private void updateList(){
    
        list1.removeAll();
        
        MaterialsJpaController mjc = new MaterialsJpaController(emf);
        
        //nalezeni si id podle kodu
        materialsEntities = mjc.findMaterialsEntities();      
        
        materialsEntities.stream().forEach((currMat) -> {
            if(currMat.getCanceled()==false){
            System.out.println(currMat.toString());
            list1.add(currMat.toString());          
            }
        }); 
        
    }
    
    
    private void jButtFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtFindMouseClicked
        // TODO add your handling code here:
       

        list1.removeAll();     
        // jmeno hledaneho obejktu
        
        String foundName;
        foundName = JtextName.getText();

        materialsEntities.stream().forEach((currMat) -> {
            if(currMat.getMaterialname().equals(foundName)){
                list1.add(currMat.toString());
            }
        });
        
    }//GEN-LAST:event_jButtFindMouseClicked

    private void jButtInDatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtInDatabaseMouseClicked
        // TODO add your handling code here:
       
        list1.removeAll();
       
        materialsEntities.stream().forEach((currMat) -> {
            if(currMat.getCanceled()==false){
            System.out.println(currMat.toString());    
            list1.add(currMat.toString());
            }
        }); 
        
        
        
    }//GEN-LAST:event_jButtInDatabaseMouseClicked

    private void jButtonCanceledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCanceledMouseClicked
        // TODO add your handling code here:
        
        list1.removeAll();
               
        materialsEntities.stream().forEach((currMat) -> {
            if(currMat.getCanceled()==true){
            System.out.println(currMat.toString());    
            list1.add(currMat.toString());
            }
        });
        
        
        
    }//GEN-LAST:event_jButtonCanceledMouseClicked

    private void jButtonAddBAckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBAckMouseClicked
        // TODO add your handling code here:
        
        MaterialsJpaController mjc = new MaterialsJpaController(emf);
        
        materialsEntities.stream().forEach((currMat) -> {
            if(currMat.toString().equals(list1.getSelectedItem().toString())){
                currMat.setCanceled(false);
                System.out.println("Back in database");
                System.out.println(currMat.getCanceled());
                try {
                    mjc.edit(currMat);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(DeleteMaterialGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(DeleteMaterialGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        updateList();
        
    }//GEN-LAST:event_jButtonAddBAckMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteMaterialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteMaterialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteMaterialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteMaterialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteToolGUI(emf).setVisible(true);
            }
        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteToolGUI(emf).setVisible(true);
            }
        });
        */
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtDelete;
    private javax.swing.JTextField JtextName;
    private javax.swing.JButton jButtFind;
    private javax.swing.JButton jButtInDatabase;
    private javax.swing.JButton jButtonAddBAck;
    private javax.swing.JButton jButtonCanceled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
