/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stois.AdminPart.Person;

import Controller.AddressesJpaController;
import Controller.InsurancesJpaController;
import Controller.PersonHasAddressJpaController;
import Controller.PersonsHasRolesJpaController;
import Controller.PersonsHasTelephonesJpaController;
import Controller.PersonsJpaController;
import Controller.RolesJpaController;
import Controller.TelephonesJpaController;
import Controller.exceptions.NonexistentEntityException;
import entity.Addresses;
import entity.Insurances;
import entity.PersonHasAddress;
import entity.Persons;
import entity.PersonsHasRoles;
import entity.PersonsHasTelephones;
import entity.Roles;
import entity.Telephones;
import java.awt.Component;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lukas
 */
public class EditPersonGUI1 extends javax.swing.JFrame {
    
    /**
     * Creates new form ToolGUI
     */
    private static EntityManagerFactory emf = null;
    private static List <Insurances> findInsurances = null;
    private static List <Persons> findPersons = null;
    private static List <Telephones> findTelephones = null;
    private static List <PersonsHasTelephones> findPersonePhone = null;
    private static List <Addresses> personAddress = null;
    private static Integer personTouched = null; 
    private static Integer phonID;
    private static boolean found = false;
    private static List <PersonHasAddress> findAddress = null;

  
    private static Addresses myAddress = null;
    private static Addresses myAddressNew = null;
    private static String printAddress = null;
    private static String addressID = null;
    
    public EditPersonGUI1(EntityManagerFactory emf) {
        this.emf = emf;
        initComponents();
        initInsurance();
        setDefaultCloseOperation(EditPersonGUI1.DISPOSE_ON_CLOSE);
        initList();
    }
    
    public EditPersonGUI1(Addresses myAddress, String printAddress){
        this.myAddress = myAddress;
        this.printAddress = printAddress;
        //initText();
    }
            
    
    public Addresses getMyAddress() {
        return myAddress;
    }

    public void setMyAddress(Addresses myAddress) {
        this.myAddress = myAddress;
    }
    
    /*
    private void initText(){
        System.out.println("blb");
        System.out.println(myAddress.toString());
        jTextAddress.setText(myAddress.toString()); 
    }
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtConfirm = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboGender = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboInsur = new javax.swing.JComboBox();
        jBirthNumber = new javax.swing.JTextField();
        jTextAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextPhone = new javax.swing.JTextField();
        list1 = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxCanceled = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Edit person");

        jFirstName.setText("First name");
        jFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstNameActionPerformed(evt);
            }
        });

        jLabel2.setText("First name:");

        jButtConfirm.setText("Confirm");
        jButtConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtConfirmMouseClicked(evt);
            }
        });

        jLabel4.setText("Surname:");

        jSurname.setText("Surname");

        jLabel5.setText("Gender:");

        jComboGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel6.setText("Birthnumber:");

        jLabel7.setText("Address:");

        jLabel8.setText("Insurance:");

        jComboInsur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Insurance" }));

        jBirthNumber.setText("Birthnumber");

        jTextAddress.setText("Address");
        jTextAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAddressMouseClicked(evt);
            }
        });
        jTextAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAddressActionPerformed(evt);
            }
        });

        jLabel9.setText("Phone number:");

        jTextPhone.setText("Phone number");

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });

        jLabel3.setText("Canceled:");

        jCheckBoxCanceled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCanceledActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("ID:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelID.setText("ID");
        jLabelID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Address");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel10)
                        .addGap(35, 35, 35)
                        .addComponent(jLabelID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCanceled)
                            .addComponent(jComboInsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSurname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBirthNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addGap(29, 29, 29)))
                                .addComponent(jButton1)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jButtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBirthNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jComboInsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCheckBoxCanceled))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initList(){
    
        list1.removeAll();
        
        PersonsJpaController perjc = new PersonsJpaController(emf); 
        findPersons = perjc.findPersonsEntities();
        TelephonesJpaController tjc = new TelephonesJpaController(emf);
        findTelephones = tjc.findTelephonesEntities();
        PersonsHasTelephonesJpaController phastjc = new PersonsHasTelephonesJpaController(emf);
        findPersonePhone = phastjc.findPersonsHasTelephonesEntities();
        PersonHasAddressJpaController phadjc = new PersonHasAddressJpaController(emf);
        findAddress = phadjc.findPersonHasAddressEntities();
        AddressesJpaController adresjpc = new AddressesJpaController(emf);
        personAddress = adresjpc.findAddressesEntities();
        
        findPersons.stream().forEach((currPer) -> {
            list1.add(currPer.toString());          
        });    
    
    }
    
    private void jButtConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtConfirmMouseClicked
        // TODO add your handling code here:
 
        AddressesJpaController adresjpc = new AddressesJpaController(emf);
        TelephonesJpaController tjc = new TelephonesJpaController(emf);
        PersonsHasTelephonesJpaController phastjc = new PersonsHasTelephonesJpaController(emf);
        PersonHasAddressJpaController phadjc = new PersonHasAddressJpaController(emf);
        PersonsJpaController perjc = new PersonsJpaController(emf); 
        
        String firstName = jFirstName.getText();
        String surName = jSurname.getText();
        String birthNum = jBirthNumber.getText();
        Boolean cancelPer = jCheckBoxCanceled.isSelected();
             
        int numGen = jComboGender.getSelectedIndex();
        boolean gen = numGen == 0 ? true : false;
        
        // nalezeni pojistovny
        
        Insurances insurObject = (Insurances)jComboInsur.getSelectedItem();
        Integer insurID = insurObject.getInsuranceid();
        
        // vyplneni udaju a nasledne prepsani v databazi
        
        findPersons.get(personTouched).setFirstname(firstName);
        findPersons.get(personTouched).setSurename(surName);
        findPersons.get(personTouched).setBirthnumber(birthNum);
        findPersons.get(personTouched).setGender(gen);
        findPersons.get(personTouched).setInsurancesInsuranceid(insurObject);
        findPersons.get(personTouched).setCanceled(cancelPer);
       
        // udaje v Persons
        try {
            perjc.edit(findPersons.get(personTouched));
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(EditPersonGUI1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(EditPersonGUI1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PersonHasAddress newPersonAddress = new PersonHasAddress(null, findPersons.get(personTouched), myAddress);
        try {
            phadjc.create(newPersonAddress);
        } catch (Exception ex) {
            Logger.getLogger(EditPersonGUI1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // to same provedu i telfonnimy cisly
        
        Integer phoneNumber = Integer.valueOf(jTextPhone.getText());
        System.out.println(phoneNumber);

        Telephones newPhone = new Telephones(null, phoneNumber, false);
        tjc.create(newPhone);
         
        //  a ted prirazni telefonu osobe
            
        PersonsHasTelephones newPersonPhone = new PersonsHasTelephones(null, findPersons.get(personTouched), newPhone);
        try {
            phastjc.create(newPersonPhone);
        } catch (Exception ex) {
            Logger.getLogger(EditPersonGUI1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println("Persons byly upraveny");
        
        initList();
       
        
    }//GEN-LAST:event_jButtConfirmMouseClicked

    private void jTextAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAddressActionPerformed
        // TODO add your handling code 
    }//GEN-LAST:event_jTextAddressActionPerformed

    private void jTextAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAddressMouseClicked
        // TODO add your handling code here:
        
        jTextAddress.setText(myAddress.toString()); 
        
    }//GEN-LAST:event_jTextAddressMouseClicked

    private void jFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstNameActionPerformed

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        // TODO add your handling code here:
        
        personTouched = list1.getSelectedIndex();
        
        jBirthNumber.setText(findPersons.get(personTouched).getBirthnumber());
        jFirstName.setText(findPersons.get(personTouched).getFirstname());
        jSurname.setText(findPersons.get(personTouched).getSurename());
        jCheckBoxCanceled.setSelected(findPersons.get(personTouched).getCanceled());
        
        boolean genderPer = findPersons.get(personTouched).getGender();
        Integer gender = genderPer == false ? 1 : 0;
        jComboGender.setSelectedIndex(gender);
        
        jComboInsur.setSelectedIndex(findPersons.get(personTouched).getInsurancesInsuranceid().getInsuranceid()-1);
        
        // jeste tam dohodim telefonni cisla a adresy
        
        TelephonesJpaController tjc = new TelephonesJpaController(emf);
        findTelephones = tjc.findTelephonesEntities();
        PersonsHasTelephonesJpaController phastjc = new PersonsHasTelephonesJpaController(emf);
        findPersonePhone = phastjc.findPersonsHasTelephonesEntities();
        
        Integer personNum = findPersons.get(personTouched).getPersonid();
        String personNumber = Integer.toString(personNum);
        jLabelID.setText(personNumber);
        
        
        findPersonePhone.stream().forEach((insur) -> {  
            if(personNum==insur.getPersonsPersonid().getPersonid()){  
                phonID = insur.getTelephonesTelephoneid().getTelephonenumber();
                System.out.println(phonID);
                found = true;

            }
            
         });
        
        
        
        //najdu si telefon u osoby
        /*
        try {
            phonID = findPersonePhone.get(personNum).getTelephonesTelephoneid().getTelephonenumber();    
        } catch (Exception e) {
            phonID = null;
        }
        */
        jTextPhone.setText("Do not known");
        
        if(found==true && phonID != null){
        jTextPhone.setText(Integer.toString(phonID));
        phonID = null;
        }
 
        // to podobne provedu i s adresama
        
         PersonHasAddressJpaController phadjc = new PersonHasAddressJpaController(emf);
         findAddress = phadjc.findPersonHasAddressEntities();
         
         findAddress.stream().forEach((currAdd) -> {  
            if(personNum==currAdd.getPersonsPersonid().getPersonid()){  
                addressID = currAdd.getAddressesAddressid().toString();
                System.out.println(addressID);
                found = true;

            }
            
         });
         
        jTextAddress.setText("Do not known");
        
        if(found==true && addressID != null){
        jTextAddress.setText(addressID);
        addressID = null;
        }
         
        /* 
        String myHome;
        System.out.println(personNum);
        try {
             myHome = findAddress.get(personNum).getAddressesAddressid().toString();
        } catch (Exception e) {
             myHome = null;
        }
        
        if(myHome !=null){
        jTextAddress.setText(myHome);
        }
        else{
        jTextAddress.setText("Do not known");
        }

        */
        
    }//GEN-LAST:event_list1MouseClicked

    private void jCheckBoxCanceledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCanceledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCanceledActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int number = 2;
        stois.AdminPart.Address.AddAddressGUI addAddresses = new stois.AdminPart.Address.AddAddressGUI(emf,number);
        addAddresses.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void initInsurance(){
        
        jComboInsur.removeAllItems();
        
        InsurancesJpaController ijc = new InsurancesJpaController(emf);
        
        findInsurances = ijc.findInsurancesEntities();
        
        findInsurances.stream().forEach((insur) -> {
            System.out.println(insur.toString());                               // vypsani pomoci toString
            jComboInsur.addItem(insur);                              // naplneni comboBoxu
        });
        
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBirthNumber;
    private javax.swing.JButton jButtConfirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxCanceled;
    private javax.swing.JComboBox jComboGender;
    private javax.swing.JComboBox jComboInsur;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jSurname;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextPhone;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
